FROM node:20-bookworm-slim AS build
WORKDIR /work

RUN npm config set fund false \
 && npm config set audit false \
 && npm config set fetch-retry-mintimeout 20000 \
 && npm config set fetch-retry-maxtimeout 120000 \
 && npm config set fetch-retry-factor 10

COPY package*.json ./
COPY .npmrc ./
COPY scripts ./scripts
COPY vendor ./vendor

ENV npm_config_optional=true

RUN npm ci --no-audit --no-fund \
 || npm install --no-audit --no-fund --legacy-peer-deps

RUN npm i -D @rollup/rollup-linux-x64-gnu --no-audit --no-fund || true

COPY . ./

RUN npm run build:web

FROM nginx:alpine
COPY --from=build /work/dist /usr/share/nginx/html
